apiVersion: vpcresources.k8s.aws/v1beta1
kind: SecurityGroupPolicy
metadata:
  name: allow-blue-to-red
  namespace: miztiik-automation-ns
labels:
    dept: engineering
    team: red-shirts
    project: eks-security-with-security-groups
spec:
  podSelector:
      matchLabels:
        role: red
  securityGroups:
      groupIds:
        - sg-0c65a538ef8abf584